### ISSUE TITLE
macOS CSS broken

### ISSUE THREAD

**Issue by onealabdulrahim** [OliverAbdulrahim/clean-firefox#1]
The macOS chrome/* customization is broken. Tabs do not render on the left, the window management is right-aligned.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14711243/216436401-c493e73c-dac5-4c34-969f-90ed346bc0be.png">

**Comment by OliverAbdulrahim** [comment]
Thanks for submitting this!

Looks like there are two issues here: 
1. The tree style tabs not are rendering
2. The window control (red, yellow, green) buttons are misplaced  

The first issue may require more work. 

The second issue may be solved by removing [lines 13 to lines 32](https://github.com/OliverAbdulrahim/clean-firefox/blob/6236d337e14dda988202c07a6c4fc7f25bd830b8/macOS/chrome/userChrome.css#L13-L32) in `macOS/chrome/userChrome.css`

**Comment by OliverAbdulrahim** [comment]
Hi @onealabdulrahim, I just pushed some changes that should address this issue on macOS. 

Here's a screenshot. It's taken while running GNOME, but I moved the window buttons to the left and applied the macOS styles:

![Screenshot from 2023-04-16 12-14-31](https://user-images.githubusercontent.com/14153661/232333365-78023191-d4dc-474b-8855-0955e39004d4.png)
